### ISSUE TITLE
Security audit link doesn't lead anywhere

### ISSUE THREAD

**Issue by raphmim** [Horizontal-org/Tella-Docs#12]
The link to open a page with the reports from security audits (in [this section](https://docs.tella-app.org/security-and-privacy#security-audits)) doesn't lead anywhere.

**Comment by carohadad** [comment]
Thanks, just fixed it https://github.com/Horizontal-org/Tella-Docs/commit/25daa7f548085871c8a9ebf98893e80e0ee320b2
